apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: python
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: python
  template:  
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: raniiaashraff/pythonapplication
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-map
        
      
        
    
